"""High-level API for convenient LLM interactions."""

# Placeholder for high-level functions
# async def generate(...): ...
# async def stream(...): ...
# async def generate_object(...): ...

__all__ = []
